using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NymnetBlogApi.Models;

namespace NymnetBlogApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]    
    public class ValuesController : ControllerBase
    {
        List<BlogPost> Posts = new List<BlogPost>
        {
            new BlogPost 
            {
                Id = 1,
                Title = "Example post",
                Summary = "This is an example post",
                Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                Author = new Author 
                {
                    Id = 1,
                    Name = "Pål",
                    Description = "Hi, my name is Pål"
                },
                Tags = new string[]
                {
                    "example",
                    "post"
                }
            }
        };

        // GET api/values
        [HttpGet]
        public ActionResult<IEnumerable<BlogPost>> Get()
        {
            return Posts;
        }

        // GET api/values/5
        [HttpGet("{id}")]
        public ActionResult<BlogPost> Get(int id)
        {
            return Posts.FirstOrDefault(post => post.Id == id);
        }

        // POST api/values
        [HttpPost]
        public void Post([FromBody] BlogPost value)
        {
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] BlogPost value)
        {
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}